# frozen_string_literal: true

require_relative "canopus/version"
require_relative "canopus/data_compat"
require_relative "canopus/regexp_compat"
require_relative "canopus/match_data_compat"
require_relative "canopus/error"
require_relative "canopus/save_conflict"

require "denebola"
require "zaniah"
require "porrima"
require "thuban"
require_relative "canopus/patch"
require_relative "canopus/buffer"
require_relative "canopus/multi_buffer"
require_relative "canopus/display_map"
require_relative "canopus/editor"
require_relative "canopus/language"
require "spica"
require_relative "canopus/project"
require_relative "canopus/terminal"
require_relative "canopus/workspace"
require_relative "canopus/plugins"
require_relative "canopus/controller"
