#!/usr/bin/env ruby
# frozen_string_literal: true

require "rbconfig"
require "rubygems"
unless RUBY_ENGINE == "ruby" && (RUBY_VERSION.split(".").first(2).map(&:to_i) <=> [3, 1]) >= 0
  abort "Canopus requires CRuby 3.1 or newer."
end
unless RUBY_PLATFORM.match?(/mswin|mingw/) || RbConfig::CONFIG["YJIT_SUPPORT"] != "yes" ||
    (defined?(RubyVM::YJIT) && RubyVM::YJIT.enabled?) || ENV["CANOPUS_YJIT_REEXEC"] == "1"
  ENV["CANOPUS_YJIT_REEXEC"] = "1"
  flags = ["--yjit"]
  exec(RbConfig.ruby, *flags, __FILE__, *ARGV)
end
ENV.delete("CANOPUS_YJIT_REEXEC")
$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "canopus"
require "canopus/cli"
exit Canopus::CLI.main(ARGV)
